#!/usr/bin/env bash
# Copyright (C) 2015  Roman Zimbelmann <hut@hut.pm>
# This software is distributed under the terms of the GNU GPL version 3.

usage () {
    echo "usage: kbind [statuscommand] <key>=<action>..."
}

kbind_base () {
    # Change the terminal environment
    local stty_orig=`stty -g`
    stty -echo

    on_exit () {
        # Restore the terminal
        stty $stty_orig
    }

    # Get a single character that's typed in by the user
    getc () {
        stty raw
        dd bs=1 count=1 2>/dev/null
        stty cooked
    }

    # Print something in a specific color
    color_cmd='echo_color() { color="$1"; shift; printf "\033[1;3${color}m$@\033[00m\n"; };'

    statuscommand="$1"
    if [ "${statuscommand:1:1}" == "=" ]; then
        statuscommand=
    else
        shift
    fi

    # Print the key bindings
    for var in "$@"; do
        echo $var
    done

    # Run the statuscommand the first time
    test -n "$statuscommand" && sh -c "$color_cmd $statuscommand"

    while true; do
        input="$(getc)"

        if [ "$input" == "q" ]; then
            break
        fi

        # The " =:" part binds <SPACE> to a no-op.
        for var in "$@" " =:"; do
            if [ "${var:0:2}" == "$input"= ]; then
                ${var:2}
                test -n "$statuscommand" && sh -c "$color_cmd $statuscommand"
                break
            fi
        done
    done

    on_exit
}

kbind_base "$@"
